platform_home:
    path:      /{page}
    defaults:
        _controller: PlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

platform_view:
    path:      /advert/{id}
    defaults:
        _controller: PlatformBundle:Advert:view
    requirements:
        page: \d+

platform_add:
    path:      /add
    defaults:
        _controller: PlatformBundle:Advert:add

platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: PlatformBundle:Advert:edit
    requirements:
        page: \d+

platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: PlatformBundle:Advert:delete
    requirements:
        page: \d+
